Feature/staking free
electric-cash/electrum-cash pull request #95
Opened 2022-04-15 09:51 UTC by Jakub123Jakub123

2022-04-25 09:26 UTC, krecik requested changes

2022-04-25 09:26 UTC, krecik commented on contrib/build-wine/build-electrum-git.sh
> -mv elcash-wallet-setup.exe $NAME_ROOT-$VERSION-setup.exe
Should be elcash-wallet

2022-04-25 09:26 UTC, krecik commented on contrib/build-wine/build-electrum-git.sh
> -sha256sum dist/elcash-wallet*.exe
elcash-wallet

2022-04-25 09:26 UTC, krecik commented on contrib/build-wine/electrum.nsi
> -  !define PRODUCT_NAME "ELCASH Wallet"
ELCASH Wallet

2022-04-25 09:26 UTC, krecik commented on contrib/build-wine/electrum.nsi
> -  !define PRODUCT_WEB_SITE " https://electriccash.global/"
Proper website address.

2022-04-25 09:26 UTC, krecik commented on contrib/build-wine/electrum.nsi
> -  OutFile "dist/elcash-wallet-setup.exe"
Should be `elcash-wallet-setup.exe`

2022-04-25 09:42 UTC, krecik requested changes, later dismissed

2022-04-25 09:42 UTC, krecik commented on contrib/build-wine/build-electrum-git.sh
> +NAME_ROOT=electrum
elcash-wallet

2022-04-25 09:42 UTC, krecik commented on contrib/build-wine/build-electrum-git.sh
> +mv electrum-setup.exe $NAME_ROOT-$VERSION-setup.exe
`elcash-wallet-setup.exe`

2022-04-25 09:42 UTC, krecik commented on contrib/build-wine/build-electrum-git.sh
> +sha256sum dist/electrum*.exe
`elcash-wallet*.exe`

2022-04-25 09:42 UTC, krecik commented on contrib/build-wine/electrum.nsi
> +  OutFile "dist/electrum-setup.exe"
"dist/elcash-wallet-setup.exe"

2022-06-24 10:37 UTC, Diabelko approved these changes

2022-07-15 08:44 UTC, merged